config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  root 'offers#index'

  resources :offers do 
    resources :referrals do 
    end
  end

  resources :users, :only => [:show]

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

	belongs_to :company

	def get_referrals
		company
		# company = self.company
		# offers = company.offers
		# offers.first.referrals
	end

	def close_referral!
		#send email
		self.status = "success"
		self.save!
	end
end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :offers
	has_many :referrals, through: :offers
	has_many :admin_users
end

app/models/location.rb
class Location < ActiveRecord::Base
	has_many :offers
end

app/models/offer.rb
class Offer < ActiveRecord::Base
	belongs_to :company 
	belongs_to :location
	has_many :referrals

	acts_as_taggable
	#this offer can have a series of checks for what it wants
	
	validates_presence_of :company
end

# tag_list is a method you can call on this
# o.tag_list.add("first_name")
# o.tag_list
# => ["first_name"]

app/models/referral.rb
class Referral < ActiveRecord::Base
	belongs_to :user
	belongs_to :offer
	belongs_to :company

	accepts_nested_attributes_for :offer

	def self.current_company(company)
		where(company: company)
	end

	def close_referral!
		#send email
		self.status = "success"
		self.save!
	end
end


#create a referral

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :referrals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
	respond_to :html, :json
  before_action :set_offer, only: [:show, :edit, :update, :destroy]


	def index
		@offers = Offer.all
		respond_with @offers
	end

	def show
    @referral = Referral.create
	end

	private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      params.require(:offer).permit(:reward, :description)
    end
end

app/controllers/referrals_controller.rb
class ReferralsController < ApplicationController

	def new
		@offer = Offer.find params[:offer_id]
		@referral = Referral.new(offer: @offer)
		@tags = @offer.tag_list
	# 	# @fields = offer.attributes
	end

	# after referrals submitted
	# needs to charge 1 dollar
	# user account screen to see referrals
	# send emails to the contact user for the company

	# active admin to see referrals


	def view
		binding.pry
		# @offer = Offer.find params[:referral_id]
		# company = @offer.company
		# @offer.build_referral
		# @referral = Referral.new
		@tags = @offer.tag_list
		render 'new'
	end

	#validation

	def create
		user = current_user
		@referral = Referral.new(referral_params)
		@referral.user    = user
		@referral.offer   = Offer.find params[:offer_id]
		@referral.save!
		#has to relate to customer
		#has to relate to company
		redirect_to root_path
	end

	private

	def referral_params
		params.required(:referral).permit!
	end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def show
		user = current_user
		@referrals = user.referrals
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/referral_helper.rb
module ReferralHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kickback</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/offers/index.html.erb
<% @offers.each do |offer| %>
<%= link_to 'Show', offer %>
	<%= offer.description %><br>
<% end %>




<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
  </li>
  <%= link_to('Account', user_path(current_user)) %>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>

app/views/offers/show.html.erb
<%= @offer.description %>
<%= link_to "Refer", new_offer_referral_path(@offer) %>

app/views/referrals/new.html.erb
<%= form_for [@offer, @referral] do |f| %>
<%= @referral.offer.description %>
<% @referral.attributes.each do |a| %>
    <% if @tags.include?(a[0])  %>
        <%= f.label "#{a[0]}".to_sym %> 
        <%= f.text_field "#{a[0]}".to_sym %>
<% end %>
<% end %>
        <%= f.submit %>

<% end %>

app/views/referrals/show.html.erb
Thanks for your submission!

app/views/users/show.html.erb
<% @referrals.each do |referral| %>
	<%= referral.offer.description %>
	<% end %>